"""add_tts_aggregation_mode_to_bot_config

Revision ID: 0d82f8e4f833
Revises: 2fcbb63e5dba
Create Date: 2026-06-07 00:20:01.883211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d82f8e4f833'
down_revision: Union[str, None] = '2fcbb63e5dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('tts_aggregation_mode', sa.String(length=16), nullable=False, server_default='sentence'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'tts_aggregation_mode')
    # ### end Alembic commands ###
