"""add bot_config.auto_record

Revision ID: 26c3c9e3dec1
Revises: c7f1a2b3d4e5
Create Date: 2026-07-21 16:19:51.611499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26c3c9e3dec1'
down_revision: Union[str, None] = 'c7f1a2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('auto_record', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'auto_record')
    # ### end Alembic commands ###
