"""add_tts_provider_to_bot_config

Revision ID: 4bbd6a7f78d5
Revises: b10ceec16110
Create Date: 2026-05-27 11:19:29.271599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bbd6a7f78d5'
down_revision: Union[str, None] = 'b10ceec16110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('tts_provider', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'tts_provider')
    # ### end Alembic commands ###
