"""add stt columns to bot config

Revision ID: b10ceec16110
Revises: 18e3bec849f0
Create Date: 2026-05-20 21:52:06.242539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b10ceec16110'
down_revision: Union[str, None] = '18e3bec849f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('stt_model', sa.String(length=128), nullable=False, server_default='gpt-realtime-whisper'))
    op.add_column('bot_config', sa.Column('stt_vad_mode', sa.String(length=32), nullable=False, server_default='server'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'stt_vad_mode')
    op.drop_column('bot_config', 'stt_model')
    # ### end Alembic commands ###
