"""add_stt_delay_to_bot_config

Revision ID: eeec5c0b9e59
Revises: 4bbd6a7f78d5
Create Date: 2026-05-27 11:48:25.371114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eeec5c0b9e59'
down_revision: Union[str, None] = '4bbd6a7f78d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_config', sa.Column('stt_delay', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_config', 'stt_delay')
    # ### end Alembic commands ###
